# BukkitCurrentWeather v0.3.0
# @author     ucchy
# @license    LGPLv3
# @copyright  Copyright ucchy 2013

syncTime: true
ignoreWorlds: []
intervalTicksSyncWeater: 24000
intervalTicksSyncTime: 60
