# ${project.name} v${project.version}
# @author     ucchy
# @license    LGPLv3
# @copyright  Copyright ucchy 2013

syncTime: true
ignoreWorlds: []
intervalTicksSyncWeather: 24000
intervalTicksSyncTime: 60
